task: 'vaernn'
vae_type: 'fc'
seeds:
  - 56243789
dataset: 'ECG5000'
batch_size: 32
distribution: 'MultivariateNormal'
rnn_block: 'lstm'
rnn_n_layers: 1
rnn_nonlinearity: 'tanh'
bidirectional: false
hidden_dim: 90
latent_dim: 20
epochs: 30
learning_rate: 0.0005
dropout: 0.0
subpath_keys:
  - 'mc_estimator'
  - 'sample_size'
device: 'cuda'
compute_perf: true
runs:
  - mc_estimator: 'MVD'
    sample_size: 1
#  - mc_estimator: 'Pathwise'
#    sample_size: 1
