task: 'vaernn'
vae_type: 'fc'
seeds:
  - 56243789
  - 16403198
  - 65738917
  - 23478912
  - 11894567
dataset: 'sinusoidal_frequencies'
batch_size: 32
distribution: 'MultivariateNormal'
latent_dim: 20
rnn_block: 'lstm'
hidden_dim: 128
rnn_n_layers: 1
rnn_nonlinearity: 'tanh'
bidirectional: false
epochs: 50
learning_rate: 0.001
dropout: 0.0
device: 'cuda'
compute_perf: true
subpath_keys:
  - 'mc_estimator'
  - 'sample_size'
runs:
  - mc_estimator: 'MVD'
    sample_size: 1
    compute_variance: true
  - mc_estimator: 'Pathwise'
    sample_size: 1
  - mc_estimator: 'Pathwise'
    sample_size: 20
  - mc_estimator: 'Pathwise'
    sample_size: 80
    compute_variance: true
  - mc_estimator: 'Reinforce'
    sample_size: 10
  - mc_estimator: 'Reinforce'
    sample_size: 40
  - mc_estimator: 'Reinforce'
    sample_size: 80
    compute_variance: true
