task: 'polynomial'
seeds:
  - 2930489
  - 7489326
  - 3648397
  - 1286498
  - 9074185
distribution: 'normal'
latent_dim: 1
init_params:
  - 0
  - 0
epochs: 500  # each iteration is one epoch in this task.
learning_rate: 0.001
epoch_print_interval: 100
plot_label: '$mc_estimator$ $sample_size$ sample(s)'
subpath_keys:
  - 'mc_estimator'
  - 'sample_size'
device: 'cuda'
runs:
  - mc_estimator: 'Reinforce'
    sample_size: 2
  - mc_estimator: 'MVD'
    sample_size: 1
  - mc_estimator: 'Pathwise'
    sample_size: 2