task: 'polynomial'
seeds:
  - 2930489
distribution: 'normal'
latent_dim: 1
init_params:
  - 0.1
  - -1
iterations: 500
learning_rate: 0.001
plot_label: '$mc_estimator$ $sample_size$ sample(s)'
subpath_keys:
  - 'mc_estimator'
  - 'sample_size'
device: 'cuda'
runs:
  - mc_estimator: 'Reinforce'
    sample_size: 1
  - mc_estimator: 'Reinforce'
    sample_size: 2
  - mc_estimator: 'MVD'
    sample_size: 1
  - mc_estimator: 'Pathwise'
    sample_size: 1
  - mc_estimator: 'Pathwise'
    sample_size: 2