task: 'polynomial'
seeds:
  - 9074185
distribution: 'categorical'
latent_dim: 1
init_params:
  - 1
repeat_params: 100
polynomial: 'quadratic'
epochs: 1000  # each iteration is one epoch in this task.
learning_rate: 0.1
save_model_interval: 200
normalize_samples: true
mc_estimator: 'Pathwise'
sample_size: 100
subpath_keys:
  - 'gumbel_temperature'
device: 'cuda'
runs:
  - gumbel_temperature: 0.1
  - gumbel_temperature: 0.25
  - gumbel_temperature: 0.5
  - gumbel_temperature: 0.75
  - gumbel_temperature: 1.0
