task: 'polynomial'
seeds:
  - 9074185
distribution: 'categorical'
latent_dim: 1
init_params:
  - 1
repeat_params: 100
polynomial: 'sinusoid'
domain: 2  # categorical output between 0 and 1.
epochs: 10000  # each iteration is one epoch in this task.
learning_rate: 0.1
save_model_interval: 2000
mc_estimator: 'Pathwise'
sample_size: 100
subpath_keys:
  - 'gumbel_temperature'
device: 'cuda'
runs:
  - gumbel_temperature: 1.0
  - gumbel_temperature: 2.0
  - gumbel_temperature: 3.0
  - gumbel_temperature: 4.0
  - gumbel_temperature: 5.0
