task: 'polynomial'
seed: 2930489
mc_estimator: 'Pathwise'
selector_estimator: 'MVD'
distribution: 'GaussianMixture'
param_dims:
  # Number of components
  - 3
  # Dimensions of mean/std
  - 2
  - 2
init_params:
  # Categorical params (normalized via softmax)
  - 1
  - 1
  - 1
  # First component
  # mean
  - -2
  - -3
  # log(std)
  - -1
  - -1
  # Second component (mean, log(std))
  # mean
  - -0.1
  - 0.1
  # log(std)
  - -1
  - -1
  # Third component (mean, log(std))
  # mean
  - 3
  - 2
  # log(std)
  - -1
  - -1
train_std: False
with_kl: False
epochs: 1000
sample_size: 1
learning_rate: 0.01
device: 'cuda:0'
