task: 'polynomial'
seeds:
  - 2930489
mc_estimator: 'MVD'
selector_estimator: 'MVD'
distribution: 'GaussianMixture'
n_components: 3
latent_dim: 1
init_params:
  - 0.3333
  - 0.3333
  - 0.3334
  - -1.0
  - 0.1
  - 0.0
  - 0.1
  - 2.0
  - 0.1
epochs: 500
sample_size: 1
learning_rate: 0.001
device: 'cuda'