task: 'polynomial'
seeds:
  - 9074185
distribution: 'normal'
latent_dim: 1
init_params:
  - 0
  - 0
polynomial: 'quadratic_flat'
epochs: 5  # each iteration is one epoch in this task.
learning_rate: 0.1
save_model_interval: 1
subpath_keys:
  - 'mc_estimator'
  - 'sample_size'
device: 'cuda'
runs:
  - mc_estimator: 'Reinforce'
    sample_size: 4
  - mc_estimator: 'MVD'
    sample_size: 1
  - mc_estimator: 'Pathwise'
    sample_size: 4