task: 'logreg'
seeds:
  - 2930489
  - 4063329
  - 4637380
  - 8463906
  - 8945623
dataset: 'cancer'
batch_size: 32
distribution: 'MultivariateNormal'
epochs: 100
learning_rate: 0.001
device: 'cuda'
runs:
  - mc_estimator: 'reinforce'
    plot_label: 'Reinforce 10 samples'
    sample_size: 10
  - mc_estimator: 'reinforce'
    plot_label: 'Reinforce 120 samples'
    sample_size: 120
  - mc_estimator: 'mvd'
    plot_label: 'MVD 1 sample'
    sample_size: 1
  - mc_estimator: 'pathwise'
    plot_label: 'Pathwise 1 sample'
    sample_size: 1
  - mc_estimator: 'pathwise'
    plot_label: 'Pathwise 120 samples'
    sample_size: 120
