task: 'logreg'
seed: 2930489
dataset: 'cancer'
batch_size: 32
mc_estimator: 'pathwise'
distribution: 'MultivariateNormal'
param_dims:
  - 30
  - 30
epochs: 50
sample_size: 120
learning_rate: 0.001
device: 'cuda:0'
