task: 'logreg'
seeds:
  - 2930489
dataset: 'cancer'
batch_size: 32
mc_estimator: 'pathwise'
distribution: 'MultivariateNormal'
latent_dim: 30
epochs: 100
sample_size: 1
learning_rate: 0.001
device: 'cuda'