task: 'vae'
vae_type: 'fc'
seeds:
  - 56243789
  - 48937968
  - 89671468
  - 12378098
  - 76432914
dataset: 'MNIST'
batch_size: 128
distribution: 'MultivariateNormal'
hidden_dims:
  - 100
epochs: 10
learning_rate: 0.001
mc_estimator: 'reinforce'
sample_size: 100
compute_variance: True
subpath_keys:
  - 'latent_dim'
device: 'cuda'
runs:
  - latent_dim: 18
  - latent_dim: 20
  - latent_dim: 22
  - latent_dim: 24