task: 'vae'
vae_type: 'fc'
seeds:
  - 56243789
  #- 16403198
  #- 65738917
  #- 23478912
  #- 11894567
dataset: 'MNIST'
batch_size: 128
distribution: 'MultivariateNormal'
hidden_dims:
  - 400
latent_dim: 20
epochs: 10
learning_rate: 0.001
sample_size: 1
subpath_keys:
  - 'mc_estimator'
  - 'mv_dims'
device: 'cuda'
variance_interval: 20
runs:
  - mc_estimator: 'MVSF'
    mv_dims: 5
  - mc_estimator: 'MVSF'
    mv_dims: 10
  - mc_estimator: 'MVSF'
    mv_dims: 15
