task: 'vae'
vae_type: 'fc'
seeds:
  - 56243789
  - 16403198
  - 65738917
  - 23478912
  - 11894567
dataset: 'MNIST'
batch_size: 128
distribution: 'MultivariateNormal'
hidden_dims:
  - 400
latent_dim: 20
epochs: 10
learning_rate: 0.001
subpath_keys:
  - 'mc_estimator'
  - 'sample_size'
device: 'cuda'
runs:
  - mc_estimator: 'Reinforce'
    sample_size: 10
  - mc_estimator: 'Reinforce'
    sample_size: 80
  - mc_estimator: 'MVD'
    sample_size: 1
  - mc_estimator: 'Pathwise'
    sample_size: 1
  - mc_estimator: 'Pathwise'
    sample_size: 80
