task: 'vae'
vae_type: 'fc'
seeds:
  - 56243789
  - 16403198
  - 65738917
  - 23478912
  - 11894567
dataset: 'MNIST'
batch_size: 128
distribution: 'MultivariateNormal'
hidden_dims:
  - 400
latent_dim: 20
epochs: 10
learning_rate: 0.001
subpath_keys:
  - 'mc_estimator'
  - 'sample_size'
device: 'cuda'
variance_interval: 20
runs:
  - mv_dims: 0
    mc_estimator: 'SF'
    sample_size: 60
  - mv_dims: 0
    mc_estimator: 'SF'
    sample_size: 40
  - mv_dims: 0
    mc_estimator: 'SF'
    sample_size: 30
  - mv_dims: 5  # 5 MV dims means MV estimate takes 20 loss evaluations
    mc_estimator: 'MVSF'
    sample_size: 40  # sample size is just for SF; MVD is always set to 1
  - mv_dims: 5  # 5 MV dims means MV estimate takes 20 loss evaluations
    mc_estimator: 'MVSF'
    sample_size: 20  # sample size is just for SF; MVD is always set to 1
  - mv_dims: 5  # 5 MV dims means MV estimate takes 20 loss evaluations
    mc_estimator: 'MVSF'
    sample_size: 10  # sample size is just for SF; MVD is always set to 1
