task: 'vae'
vae_type: 'fc'
seeds:
  - 56243789
  - 16403198
  - 65738917
  - 23478912
  - 11894567
dataset: 'MNIST'
batch_size: 128
distribution: 'MultivariateNormal'
hidden_dims:
  - 400
latent_dim: 20
epochs: 10
learning_rate: 0.001
device: 'cuda'
runs:
  #- mc_estimator: 'reinforce'
  #  plot_label: 'Reinforce 10 samples'
  #  sample_size: 10
  - mc_estimator: 'reinforce'
    plot_label: 'Reinforce 40 samples'
    sample_size: 40
  - mc_estimator: 'mvd'
    plot_label: 'MVD 1 sample'
    sample_size: 1
  #- mc_estimator: 'pathwise'
  #  plot_label: 'Pathwise 1 sample'
  #  sample_size: 1
  - mc_estimator: 'pathwise'
    plot_label: 'Pathwise 40 samples'
    sample_size: 40