task: 'vae'
seed: 2930489
dataset: 'MNIST'
batch_size: 64
mc_estimator: 'mvd'
distribution: 'MultivariateNormal'
hidden_dim: 50
param_dims:
  - 3
  - 3
latent_dim: 3
epochs: 10
sample_size: 7
learning_rate: 0.001
device: 'cuda:0'