task: 'vae'
seed: 2930489
dataset: 'MNIST'
batch_size: 64
mc_estimator: 'mvd'
distribution: 'MultivariateNormal'
hidden_dim: 200
param_dims:
  - 15
  - 15
train_std: False
latent_dim: 15
epochs: 10
sample_size: 1
learning_rate: 0.0001
device: 'cuda:0'