task: 'vae'
vae_type: 'conv2d'
seeds:
  - 85690467
dataset: 'Omniglot'
batch_size: 144
distribution: 'MultivariateNormal'
hidden_dims:
  - 32
  - 64
  - 128
  - 256
latent_dim: 20
epochs: 20
learning_rate: 0.0001
plot_label: '$mc_estimator$ $sample_size$ sample(s)'
subpath_keys:
  - 'mc_estimator'
  - 'sample_size'
device: 'cuda'
runs:
  - mc_estimator: 'Reinforce'
    sample_size: 10
  - mc_estimator: 'Reinforce'
    sample_size: 40
  - mc_estimator: 'MVD'
    sample_size: 1
  - mc_estimator: 'Pathwise'
    sample_size: 1
  - mc_estimator: 'Pathwise'
    sample_size: 40
