task: 'vae'
vae_type: 'conv2d'
seeds:
  - 85690467
dataset: 'Omniglot'
batch_size: 144
distribution: 'MultivariateNormal'
hidden_dims:
  - 32
  - 64
  - 128
  - 256
latent_dim: 20
epochs: 20
learning_rate: 0.0001
device: 'cuda'
runs:
  - mc_estimator: 'reinforce'
    plot_label: 'Reinforce 10 samples'
    sample_size: 10
  - mc_estimator: 'reinforce'
    plot_label: 'Reinforce 40 samples'
    sample_size: 40
  - mc_estimator: 'mvd'
    plot_label: 'MVD 1 sample'
    sample_size: 1
  - mc_estimator: 'pathwise'
    plot_label: 'Pathwise 1 sample'
    sample_size: 1
  - mc_estimator: 'pathwise'
    plot_label: 'Pathwise 40 sample'
    sample_size: 40
