task: 'vae'
seed: 2930489
dataset: 'MNIST'
batch_size: 128
mc_estimator: 'pathwise'
distribution: 'MultivariateNormal'
hidden_dim: 400
param_dims:
  - 20
  - 20
latent_dim: 20
epochs: 10
sample_size: 1
learning_rate: 0.001
device: 'cuda'