task: 'vae'
seed: 2930489
dataset: 'MNIST'
batch_size: 64
mc_estimator: 'pathwise'
distribution: 'MultivariateNormal'
hidden_dim: 300
param_dims:
  - 15
  - 15
latent_dim: 15
epochs: 20
sample_size: 1
learning_rate: 0.001
device: 'cuda'