task: 'vae'
seed: 2930489
dataset: 'MNIST'
batch_size: 64
mc_estimator: 'reinforce'
distribution: 'MultivariateNormal'
hidden_dim: 100
param_dims:
  - 2
  - 2
latent_dim: 2
epochs: 10
sample_size: 1000
learning_rate: 0.00001
device: 'cuda:0'